name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-14

      - name: Check C++ formatting
        run: |
          echo "Checking C++ code formatting..."
          find Code -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format-14 --dry-run --Werror
          echo "✓ Code formatting is correct"

  cmake-lint:
    name: CMake Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cmakelang
        run: |
          pip install cmakelang

      - name: Run cmake-lint
        run: |
          echo "Linting CMakeLists.txt..."
          cmake-lint --disabled-codes C0103,C0111 CMakeLists.txt
          echo "✓ CMake files look good"

  powershell-lint:
    name: PowerShell Script Analysis
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path Build.ps1 -Severity Error
          Write-Host "✓ PowerShell script analysis passed"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3